#!/usr/bin/env python3
"""
Generate the three downloadable Excel templates used by the Playbook
chapters at /playbooks/01-dsar, /playbooks/02-breach, /playbooks/03-vendor-vet.

Outputs:
  docs/public/checklists/dsar-log.xlsx
  docs/public/checklists/breach-triage.xlsx
  docs/public/checklists/vendor-register.xlsx

Run:
  pip install openpyxl
  python tools/generate-checklists.py

Each workbook has one sheet, bold headers, frozen top row, sensible
column widths, one example row in italic grey, and a footer line linking
back to the playbook chapter that explains how to use it.
"""

from datetime import datetime, timezone
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter


OUTPUT_DIR = Path(__file__).resolve().parents[1] / "docs" / "public" / "checklists"
SITE_BASE = "https://whatsdd.github.io/GDPR-in-60-minutes"
CREATOR = "GDPR by Noor"
FIXED_TS = datetime(2025, 1, 1, 0, 0, 0, tzinfo=timezone.utc)


def style_header_row(sheet, columns):
    header_font = Font(bold=True, color="FFFFFF")
    header_fill = PatternFill("solid", fgColor="003399")
    centered = Alignment(horizontal="left", vertical="center", wrap_text=True)
    for idx, (label, width) in enumerate(columns, start=1):
        cell = sheet.cell(row=1, column=idx, value=label)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = centered
        sheet.column_dimensions[get_column_letter(idx)].width = width
    sheet.row_dimensions[1].height = 26
    sheet.freeze_panes = "A2"


def add_example_row(sheet, values):
    italic_grey = Font(italic=True, color="888888")
    for idx, value in enumerate(values, start=1):
        cell = sheet.cell(row=2, column=idx, value=value)
        cell.font = italic_grey
        cell.alignment = Alignment(vertical="top", wrap_text=True)


def add_footer(sheet, last_col, message_row, message):
    sheet.cell(row=message_row, column=1, value=message).font = Font(
        italic=True, color="555555", size=9
    )
    sheet.merge_cells(
        start_row=message_row,
        start_column=1,
        end_row=message_row,
        end_column=last_col,
    )


def standardise(workbook):
    """Pin metadata so re-runs produce nearly identical bytes."""
    workbook.properties.creator = CREATOR
    workbook.properties.lastModifiedBy = CREATOR
    workbook.properties.created = FIXED_TS
    workbook.properties.modified = FIXED_TS
    workbook.properties.title = "GDPR by Noor template"
    workbook.properties.subject = "Companion checklist"
    workbook.properties.description = "See playbook chapter for usage."
    workbook.properties.keywords = "GDPR, checklist, playbook"
    workbook.properties.category = "Privacy templates"


def build_dsar_log() -> Workbook:
    wb = Workbook()
    sheet = wb.active
    sheet.title = "DSAR Log"
    columns = [
        ("Request ID", 14),
        ("Received date", 14),
        ("Type", 18),
        ("Requester name", 22),
        ("Requester contact", 26),
        ("Identity verified", 16),
        ("Systems searched", 32),
        ("Bundle delivered date", 18),
        ("Days elapsed", 12),
        ("Redactions made", 30),
        ("Outcome", 18),
        ("Notes", 40),
    ]
    style_header_row(sheet, columns)
    add_example_row(
        sheet,
        [
            "DSAR-2026-001",
            "2026-05-02",
            "Access (Art. 15)",
            "Jane Doe",
            "jane@example.com",
            "Yes, magic-link",
            "Product DB, Help-desk, Email tool",
            "2026-05-28",
            26,
            "Third-party employee names redacted",
            "Fulfilled",
            "Bundle delivered as ZIP. Cover letter sent.",
        ],
    )
    add_footer(
        sheet,
        len(columns),
        message_row=20,
        message=(
            "Template generated by the GDPR by Noor companion site. "
            f"See the runbook at {SITE_BASE}/playbooks/01-dsar."
        ),
    )
    return wb


def build_breach_triage() -> Workbook:
    wb = Workbook()
    sheet = wb.active
    sheet.title = "Breach Triage"
    columns = [
        ("Incident ID", 14),
        ("Detected date", 14),
        ("Detected time", 14),
        ("Detected by", 18),
        ("Type (C/I/A)", 14),
        ("Description", 36),
        ("Data categories affected", 26),
        ("Approx. people affected", 18),
        ("Risk level", 12),
        ("72h deadline", 14),
        ("Authority notified date", 18),
        ("Notify data subjects", 18),
        ("Subjects notified date", 18),
        ("Containment actions", 30),
        ("Root cause", 26),
        ("Lessons", 30),
        ("Status", 12),
    ]
    style_header_row(sheet, columns)
    add_example_row(
        sheet,
        [
            "INC-2026-014",
            "2026-04-18",
            "03:15",
            "On-call alert",
            "Confidentiality",
            "Ransomware on production DB cluster A",
            "Account email, name, hashed password",
            240000,
            "High",
            "2026-04-21",
            "2026-04-19",
            "Yes",
            "2026-04-20",
            "Network isolation, restore from backup",
            "Outdated VPN appliance, unpatched CVE",
            "Patch SLA tightened to 7 days for critical CVEs",
            "Closed",
        ],
    )
    add_footer(
        sheet,
        len(columns),
        message_row=20,
        message=(
            "Template generated by the GDPR by Noor companion site. "
            f"See the runbook at {SITE_BASE}/playbooks/02-breach."
        ),
    )
    return wb


def build_vendor_register() -> Workbook:
    wb = Workbook()
    sheet = wb.active
    sheet.title = "Vendor Register"
    columns = [
        ("Vendor name", 22),
        ("Service", 22),
        ("Role", 22),
        ("Country of processing", 18),
        ("Sub-processors", 30),
        ("DPA signed date", 16),
        ("DPA expiry", 14),
        ("Data categories", 26),
        ("Lawful basis", 22),
        ("Transfer mechanism", 22),
        ("Security reviewed", 18),
        ("Last review date", 16),
        ("Next review date", 16),
        ("Risk rating", 14),
        ("Owner", 18),
        ("Status", 12),
    ]
    style_header_row(sheet, columns)
    add_example_row(
        sheet,
        [
            "PostBolt",
            "Transactional email",
            "Processor",
            "Ireland (EU)",
            "AWS Ireland, Cloudflare, postal-test-tool",
            "2025-04-12",
            "2026-04-12",
            "Customer email, name",
            "Contract necessity",
            "EEA, no transfer",
            "Yes (SOC 2 Type II)",
            "2025-10-01",
            "2026-04-01",
            "Low",
            "Florinha",
            "Active",
        ],
    )
    add_footer(
        sheet,
        len(columns),
        message_row=20,
        message=(
            "Template generated by the GDPR by Noor companion site. "
            f"See the runbook at {SITE_BASE}/playbooks/03-vendor-vet."
        ),
    )
    return wb


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    plans = [
        ("dsar-log.xlsx", build_dsar_log()),
        ("breach-triage.xlsx", build_breach_triage()),
        ("vendor-register.xlsx", build_vendor_register()),
    ]
    for filename, workbook in plans:
        standardise(workbook)
        output_path = OUTPUT_DIR / filename
        workbook.save(output_path)
        print(f"wrote {output_path.relative_to(OUTPUT_DIR.parents[2])}")


if __name__ == "__main__":
    main()
